# Generated by Django 2.0.6 on 2018-06-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180613_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_mtm', to='booking.Book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to='booking.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags_mtm',
            field=models.ManyToManyField(related_name='book_mtm', through='booking.BookTags', to='booking.Tag'),
        ),
    ]
