# Generated by Django 2.0.6 on 2018-06-09 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a34bbc4-c563-4344-b755-3461add3dc3c'), primary_key=True, serialize=False),
        ),
    ]
