# Generated by Django 2.0.6 on 2018-06-20 15:37

from django.db import migrations


def migrate_tasks(apps, schema_editor):
    Task = apps.get_model('myapp', 'Task')
    Task.objects.create(text='task1', checked=True)
    Task.objects.create(text='task2', checked=False)
    Task.objects.create(text='task3', checked=False)

class Migration(migrations.Migration):


    dependencies = [
        ('myapp', '0003_auto_20180609_0831'),
    ]

    operations = [
        migrations.RunPython(migrate_tasks)
    ]
